[package]
name = "timecard-api-rust"
version = "1.3.4"
authors = [ "tozastation <ryo.for.development@gmail.com>" ]

[dependencies]
hyper = "0.12"
serde_json = "1.0"
futures = "0.1"
uuid = "0.7"
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"